[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "w0rng", email = "me@w0rng.ru"},
]
dependencies = [
    "aiohttp>=3.8.3",
    "gunicorn>=20.1.0",
    "dnspython>=2.2.1",
]
requires-python = ">=3.11"
license = {text = "MIT"}
